### ISSUE TITLE
NotImplementedError: The image and the kernel must have the same type.inputs

### ISSUE THREAD

**Issue by fliuzzi** [flipkart-incubator/optimus#6]
Hi, Im trying to utilize the GPU to train on EC2 with a g2 instance, but on all sorts of configuration types I get this error.  Im using theano 0.7 and have changed FloatX=float32 and device=gpu0
This doesn't work, and I noticed that this happens with yoon's original code too.  

Has anyone found a way around this error?

If anybody has a configuration where GPU computation is working, please post your config!
Thanks!

**Comment by fliuzzi** [comment]
To add to this, even when i seem to set up the gpu and config perfectly and without errors, it just doesn't run at all, and is obviously still using the CPU.  Here are two runs:  the first i use the gpu device and the second i use the cpu

---

ubuntu@ip-10-13-207-39:/mnt/frankie/optimus$ time python train.py sample/configs/sampleNonStaticConfig.json sample/datasets/sst_small_sample.csv sample/myFirstModel.p true
**Using gpu device 0: GRID K520**
Converted word vectors to word_idx_map
Converted the dataset into matrix. Num Rows =  300  Num labels =  2
Parameters for model:  [('image shape', 64, 300), ('filter shape', [(100, 1, 3, 300), (100, 1, 4, 300), (100, 1, 5, 300)]), ('hidden_units', []), ('dropout', 0.5), ('batch_size', 50), ('learn_decay', 0.95), ('conv_non_linear', u'relu'), ('mode', u'nonstatic'), ('sqr_norm_lim', 9), ('shuffle_batch', True), ('n_epochs', 5)]
epoch 1, train perf 65.600000 %, val perf 48.000000
epoch 2, train perf 50.800000 %, val perf 40.000000
epoch 3, train perf 50.800000 %, val perf 40.000000
epoch 4, train perf 56.400000 %, val perf 44.000000
epoch 5, train perf 88.400000 %, val perf 68.000000
Training finished. Best model is at  sample/myFirstModel.p

real    1m26.142s
user    1m24.769s
sys 0m1.841s

__________________AND WITH CPU ...

ubuntu@ip-10-13-207-39:/mnt/frankie/optimus$ nano ~/.theanorc
ubuntu@ip-10-13-207-39:/mnt/frankie/optimus$ time python train.py sample/configs/sampleNonStaticConfig.json sample/datasets/sst_small_sample.csv sample/myFirstModel.p true
Converted word vectors to word_idx_map
Converted the dataset into matrix. Num Rows =  300  Num labels =  2
Parameters for model:  [('image shape', 64, 300), ('filter shape', [(100, 1, 3, 300), (100, 1, 4, 300), (100, 1, 5, 300)]), ('hidden_units', []), ('dropout', 0.5), ('batch_size', 50), ('learn_decay', 0.95), ('conv_non_linear', u'relu'), ('mode', u'nonstatic'), ('sqr_norm_lim', 9), ('shuffle_batch', True), ('n_epochs', 5)]
epoch 1, train perf 65.600000 %, val perf 48.000000
epoch 2, train perf 50.800000 %, val perf 40.000000
epoch 3, train perf 50.800000 %, val perf 40.000000
epoch 4, train perf 56.400000 %, val perf 44.000000
epoch 5, train perf 88.400000 %, val perf 68.000000
Training finished. Best model is at  sample/myFirstModel.p

real    1m26.366s
user    1m24.861s
sys 0m1.906s

**Comment by devashishshankar** [comment]
The code should work seamlessly on GPUs. I have tested it. The only changes you have to make are for Theano. (E.g. FloatX=float32 and device=gpu0). Seems from your outputs, you were able to run on GPUs. You won't see GPU speedup on such a small dataset. This is because some time is spent on setting up GPUs, copying data from CPU memory to GPU memory, etc.

Did you try on a larger dataset?

**Comment by devashishshankar** [comment]
Hi, Thanks for notifying this! There actually was a bug when using GPUs. Using floatX = float64 is not the correct solution and makes it use CPUs. This should be fixed now.
